[package]
name = "mal-discord-widget"
version = "2.1.0"
edition = "2024"
authors = [ "Benjamin (svn)" ]
description = "Scrape a users MAL page and send the data to a custom Discord Widget"
repository = "https://github.com/7games/mal-discord-widget"
license = "Unlicense"

[dependencies]
dotenv = "0.15.0"
reqwest = { version = "0.13.4", features = [ "blocking", "json" ] }
scraper = "0.27.0"
serde_json = "1.0.151"
time = { version = "0.3.51", features = [ "parsing", "formatting", "macros" ] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
